In [24]:
# grep -i "gw01.extranet.frachtwerk.de filterlog" pfsense.log > pfsense.csv
import pandas

In [29]:
df = pandas.read_csv("~/Downloads/pfsense2.csv", sep=',', header=None, names=range(30))

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (17,20,21,24,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [37]:
df.head(100)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,Sep 7 11:45:50 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1599469328,vtnet3,match,block,in,4,0x0,...,51636,443,0.0,R,3551626076,NaN,0.0,NaN,NaN,NaN
1,Sep 7 11:45:52 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1599469328,vtnet3,match,block,in,4,0x0,...,51652,443,0.0,R,900156233,NaN,0.0,NaN,NaN,NaN
2,Sep 7 11:46:00 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1599469328,vtnet3,match,block,in,4,0x0,...,51704,443,0.0,R,319724059,NaN,0.0,NaN,NaN,NaN
3,Sep 7 11:46:00 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1599469328,vtnet3,match,block,in,4,0x0,...,51704,443,0.0,R,319724059,NaN,0.0,NaN,NaN,NaN
4,Sep 7 11:46:12 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1599469328,vtnet3,match,block,in,4,0x0,...,51770,443,0.0,R,3030680876,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sep 7 11:49:14 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1597937078,vtnet0,match,block,in,4,0x0,...,36030,17185,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Sep 7 11:49:16 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1597937078,vtnet0,match,block,in,4,0x8,...,21708,65432,0.0,RA,0,2.47846e+09,0.0,NaN,NaN,NaN
97,Sep 7 11:49:19 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1597937078,vtnet0,match,block,in,4,0x0,...,60000,99,0.0,S,4162705714,NaN,1024.0,NaN,NaN,NaN
98,Sep 7 11:49:21 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1597937078,vtnet0,match,block,in,4,0x0,...,63492,445,0.0,S,699226624,NaN,8192.0,NaN,mss;nop;wscale;nop;nop;sackOK,NaN
99,Sep 7 11:49:22 gw01.extranet.frachtwerk.de fi...,NaN,NaN,1597937078,vtnet0,match,block,in,4,0x0,...,34962,10035,0.0,S,1789202234,NaN,1024.0,NaN,mss,NaN